{{- if .Values.httpRoute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "dependencytrack.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.httpRoute.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.httpRoute.labels }}
  labels: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.httpRoute.parentRefs }}
  parentRefs: {{- toYaml . | nindent 2 }}
  {{- end }}
  hostnames:
  {{- range .Values.httpRoute.hostnames }}
  - {{ . | quote }}
  {{- end }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /api
    backendRefs:
    - name: {{ include "dependencytrack.apiServerFullname" . }}
      port: 8080
  - matches:
    - path:
        type: PathPrefix
        value: /health
    backendRefs:
    - name: {{ include "dependencytrack.apiServerFullname" . }}
      port: 8080
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ include "dependencytrack.frontendFullname" . }}
      port: 8080
{{- end }}
