{{- if eq .Values.apiServer.deploymentType "Deployment" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dependencytrack.apiServerFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "dependencytrack.apiServerLabels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "dependencytrack.apiServerSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "dependencytrack.apiServerSelectorLabels" . | nindent 8 }}
      {{- if .Values.apiServer.extraPodLabels }}
      {{- toYaml .Values.apiServer.extraPodLabels | nindent 8 }}
      {{- end }}
      annotations:
        {{- if .Values.apiServer.metrics.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        {{- end }}
        {{- with .Values.apiServer.annotations }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
    spec:
      enableServiceLinks: {{ .Values.common.enableServiceLinks }}
      {{- with .Values.common.image.pullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 6 }}
      {{- end }}
      initContainers:
      {{- with .Values.apiServer.initContainers }}
      {{- tpl (toYaml .) $ | nindent 6 }}
      {{- end }}
      serviceAccountName: {{ include "dependencytrack.serviceAccountName" . }}
      {{- with .Values.apiServer.podSecurityContext }}
      securityContext: {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ include "dependencytrack.apiServerName" . }}
        image: {{ include "dependencytrack.apiServerImage" . }}
        imagePullPolicy: {{ .Values.apiServer.image.pullPolicy }}
        securityContext: {{ toYaml .Values.apiServer.securityContext | nindent 10 }}
        {{- with .Values.apiServer.command }}
        command: {{ toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.apiServer.args }}
        args: {{ toYaml . | nindent 8 }}
        {{- end }}
        resources: {{- toYaml .Values.apiServer.resources | nindent 10 }}
        env:
        - name: ALPINE_METRICS_ENABLED
          value: "true"
        {{- if (include "dependencytrack.secretKeySecretName" .) }}
        - name: ALPINE_SECRET_KEY_PATH
          value: "/var/run/secrets/secret.key"
        {{- end }}
        {{- with .Values.apiServer.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.apiServer.extraEnvFrom }}
        envFrom: {{ toYaml . | nindent 8 }}
        {{- end }}
        ports:
        - name: web
          containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /data
        - name: tmp
          mountPath: /tmp
        {{- if (include "dependencytrack.secretKeySecretName" .) }}
        - name: secret-key
          subPath: secret.key
          mountPath: /var/run/secrets/secret.key
          readOnly: true
        {{- end }}
        {{- if .Values.apiServer.additionalVolumeMounts }}
          {{- toYaml .Values.apiServer.additionalVolumeMounts | nindent 8 }}
        {{- end }}
        livenessProbe:
          httpGet:
            scheme: HTTP
            port: web
            path: /health/live
          failureThreshold: {{ .Values.apiServer.probes.liveness.failureThreshold }}
          initialDelaySeconds: {{ .Values.apiServer.probes.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.apiServer.probes.liveness.periodSeconds }}
          successThreshold: {{ .Values.apiServer.probes.liveness.successThreshold }}
          timeoutSeconds: {{ .Values.apiServer.probes.liveness.timeoutSeconds }}
        readinessProbe:
          httpGet:
            scheme: HTTP
            port: web
            path: /health/ready
          failureThreshold: {{ .Values.apiServer.probes.readiness.failureThreshold }}
          initialDelaySeconds: {{ .Values.apiServer.probes.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.apiServer.probes.readiness.periodSeconds }}
          successThreshold: {{ .Values.apiServer.probes.readiness.successThreshold }}
          timeoutSeconds: {{ .Values.apiServer.probes.readiness.timeoutSeconds }}
      {{- with .Values.apiServer.extraContainers }}
      {{- tpl (toYaml .) $ | nindent 6 }}
      {{- end }}
      {{- if .Values.apiServer.tolerations }}
      tolerations:
      {{- toYaml .Values.apiServer.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.apiServer.nodeSelector }}
      nodeSelector:
      {{- toYaml .Values.apiServer.nodeSelector | nindent 8 }}
      {{- end }}
      volumes:
      - name: data
        {{- if .Values.apiServer.persistentVolume.enabled }}
        persistentVolumeClaim:
          claimName: {{ if .Values.apiServer.persistentVolume.existingClaim }}{{ .Values.apiServer.persistentVolume.existingClaim }}{{- else }}{{ include "dependencytrack.fullname" . }}-apiserver{{- end }}
        {{- else }}
        emptyDir: { }
        {{- end }}
      - name: tmp
        emptyDir: { }
      {{- if .Values.apiServer.additionalVolumes }}
        {{- toYaml .Values.apiServer.additionalVolumes | nindent 6 }}
      {{- end }}
      {{- with (include "dependencytrack.secretKeySecretName" .) }}
      - name: secret-key
        secret:
          secretName: {{ . }}
      {{- end }}
  {{- end }}
