---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dependencytrack.apiServerFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "dependencytrack.apiServerLabels" . | nindent 4 }}
  {{- if .Values.apiServer.service.annotations }}
  annotations:
  {{ toYaml .Values.apiServer.service.annotations | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.apiServer.service.type | quote }}
  ports:
  - name: http
    port: 8080
    targetPort: http
    {{- with .Values.apiServer.service.nodePort }}
    nodePort: {{ . }}
    {{- end }}
  selector: {{- include "dependencytrack.apiServerSelectorLabels" . | nindent 4 }}
